[package]
name = "mfg_pde_rust_experimental"
version = "0.1.0"
edition = "2021"

[lib]
name = "mfg_pde_rust_experimental"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"

[profile.release]
lto = true
codegen-units = 1
