# Minimal pyvista stub for MFG_PDE strategic typing
# Focus on classes and functions actually used in MFG_PDE

from typing import Any
import numpy as np
from numpy.typing import NDArray

# Core pyvista classes used in MFG_PDE
class UnstructuredGrid:
    def __init__(self, cells: Any = None, cell_types: Any = None, points: Any = None) -> None: ...
    def plot(self, **kwargs: Any) -> Any: ...

class PolyData:
    def __init__(self, points: NDArray[np.floating] | None = None, **kwargs: Any) -> None: ...
    def plot(self, **kwargs: Any) -> Any: ...

class Plotter:
    def __init__(self, **kwargs: Any) -> None: ...
    def add_mesh(self, mesh: Any, **kwargs: Any) -> None: ...
    def add_text(self, text: str, **kwargs: Any) -> None: ...
    def show(self, **kwargs: Any) -> None: ...
    def add_axes(self) -> None: ...
    def show_grid(self) -> None: ...

# Catch-all for any missing pyvista attributes
def __getattr__(name: str) -> Any: ...
