name: mfg_env_performance
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python with performance optimizations
  - python=3.12

  # Optimized NumPy/SciPy builds with NumPy 2.0+
  - numpy>=2.0
  - scipy>=1.13
  - "blas=*=openblas"      # Use OpenBLAS for better performance
  - "lapack=*=openblas"    # Linear algebra optimizations

  # Core scientific stack
  - matplotlib>=3.8
  - pandas>=2.1

  # Performance libraries
  - numba>=0.59           # NumPy 2.0+ support
  - cython>=3.0           # C extensions
  - joblib>=1.3           # Parallel processing

  # GPU acceleration (optional)
  - jax>=0.4.20
  - jaxlib
  # - cupy               # Uncomment for CUDA GPU support

  # Memory profiling and optimization
  - psutil>=5.9
  - memory_profiler

  # Interactive computing
  - jupyter>=1.0
  - jupyterlab>=4.0
  - ipython>=8.12

  # Visualization
  - plotly>=5.17
  - bokeh>=3.3
  - seaborn>=0.13

  # Development tools
  - pytest>=7.0
  - pytest-benchmark     # Performance testing
  - black>=23.0
  - isort>=5.12
  - mypy>=1.5
  - line_profiler        # Code profiling

  # Documentation
  - sphinx>=7.0
  - sphinx-rtd-theme
  - nbsphinx             # Jupyter notebook docs

  # Package management
  - pip
  - conda-build          # For building conda packages

  - pip:
    - mpi4py             # MPI support for parallel computing
    - h5py               # HDF5 file format
    - zarr               # Cloud-optimized data storage
