name: mfg_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python (required for NumPy 2.0+)
  - python=3.12

  # Core scientific computing with NumPy 2.0+
  - numpy>=2.0             # Native NumPy 2.0+ with trapezoid
  - scipy>=1.13            # NumPy 2.0+ compatible
  - matplotlib>=3.8        # Updated for NumPy 2.0+

  # Performance libraries
  - numba>=0.59           # NumPy 2.0+ support
  - jax>=0.4.20           # Latest with NumPy 2.0+ support
  - jaxlib                # JAX support library

  # Data processing
  - pandas>=2.1           # NumPy 2.0+ compatible
  - polars>=0.20          # Fast data processing
  - h5py>=3.9             # HDF5 files

  # Interactive computing
  - jupyter>=1.0
  - jupyterlab>=4.0
  - ipython>=8.12

  # Visualization
  - plotly>=5.17          # Interactive plotting
  - bokeh>=3.3            # Advanced visualizations
  - seaborn>=0.13         # Statistical plotting

  # Development tools
  - pytest>=7.0          # Testing framework
  - pytest-benchmark     # Performance testing
  - black>=23.0          # Code formatting
  - isort>=5.12          # Import sorting
  - mypy>=1.5            # Type checking

  # Documentation
  - sphinx>=7.0          # Documentation generation
  - sphinx-rtd-theme     # RTD theme
  - nbsphinx             # Jupyter notebook docs

  # System utilities
  - psutil>=5.9          # System monitoring
  - memory_profiler      # Memory profiling
  - line_profiler        # Line-by-line profiling

  # Package management
  - pip
  - conda-build          # For building packages

  # Additional pip packages
  - pip:
    - pydantic>=2.0      # Data validation
    - igraph>=0.10       # Graph algorithms
    - texttable          # Text tables
    - typing-inspection  # Runtime type inspection
