# Minimal pandas stub for MFG_PDE strategic typing
# Focus on functions actually used in polars integration

from typing import Any

# Core pandas classes used in MFG_PDE
class DataFrameGroupBy:
    def agg(self, func: dict[str, Any] | str | list[str]) -> DataFrame: ...

class DataFrame:
    def __init__(self, data: Any = None, **kwargs: Any) -> None: ...
    def to_dict(self, orient: str = "dict") -> dict[str, Any]: ...
    def groupby(self, by: str | list[str]) -> DataFrameGroupBy: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

class Series:
    def __init__(self, data: Any = None, **kwargs: Any) -> None: ...
    def tolist(self) -> list[Any]: ...

# Core pandas functions
def read_csv(filepath: str, **kwargs: Any) -> DataFrame: ...

# Catch-all for any missing pandas attributes
def __getattr__(name: str) -> Any: ...
