# Bokeh io stub for MFG_PDE strategic typing

from typing import Any

# IO functions used in MFG_PDE
def curdoc() -> Any: ...
def push_notebook(**kwargs: Any) -> None: ...
def show(obj: Any, **kwargs: Any) -> None: ...

# Catch-all for any missing io functions
def __getattr__(name: str) -> Any: ...
