# Bokeh layouts stub for MFG_PDE strategic typing

from typing import Any

# Layout functions used in MFG_PDE
def column(*args: Any, **kwargs: Any) -> Any: ...
def gridplot(children: Any, **kwargs: Any) -> Any: ...
def row(*args: Any, **kwargs: Any) -> Any: ...

# Catch-all for any missing layout functions
def __getattr__(name: str) -> Any: ...
