# Bokeh plotting stub for MFG_PDE strategic typing

from typing import Any

# Plotting functions used in MFG_PDE
def figure(**kwargs: Any) -> Any: ...
def output_file(filename: str, **kwargs: Any) -> None: ...
def save(obj: Any, filename: str | None = None, **kwargs: Any) -> None: ...

# Catch-all for any missing plotting functions
def __getattr__(name: str) -> Any: ...
