# Base configuration for numerical methods
paradigm: numerical

# Default discretization parameters
spatial:
  grid_type: "uniform"
  nx: 128
  ny: 128
  domain: [0.0, 1.0, 0.0, 1.0]  # [xmin, xmax, ymin, ymax]

temporal:
  dt: 0.01
  T: 1.0
  scheme: "implicit_euler"

# Convergence criteria
convergence:
  tolerance: 1e-6
  max_iterations: 1000
  check_interval: 10

# Solver settings
solver:
  linear_solver: "spsolve"
  preconditioner: null
  iterative_method: "fixed_point"

# Output settings
output:
  save_history: true
  checkpoint_interval: 100
  export_format: ["numpy", "hdf5"]
