# Crowd motion MFG problem configuration
problem_type: "crowd_motion"

# Domain settings
domain:
  type: "rectangle"
  bounds: [0.0, 1.0, 0.0, 1.0]  # [xmin, xmax, ymin, ymax]
  boundary_conditions:
    type: "neumann"  # dirichlet, neumann, periodic

# Time settings
time:
  T: 1.0
  dt: 0.01

# Physical parameters
parameters:
  sigma: 0.1        # Diffusion coefficient
  alpha: 1.0        # Running cost weight
  beta: 1.0         # Congestion cost weight

# Running cost L(x, v, m)
running_cost:
  type: "quadratic_control_congestion"
  control_weight: 0.5     # |v|²/2 term
  congestion_weight: 1.0  # m(x) term

# Terminal cost g(x)
terminal_cost:
  type: "distance_to_target"
  target: [0.8, 0.8]
  weight: 1.0

# Initial density m₀(x)
initial_density:
  type: "gaussian"
  center: [0.2, 0.2]
  variance: 0.05
  normalize: true

# Obstacles (optional)
obstacles:
  - type: "circle"
    center: [0.5, 0.5]
    radius: 0.1
    penalty: 1000.0

# Verification settings
verification:
  check_mass_conservation: true
  check_nash_equilibrium: true
  tolerance: 1e-6
