# Base MFG Problem Configuration
# Common settings for all MFG problems

problem:
  name: "base_mfg_problem"
  type: "generic"
  description: "Base Mean Field Game problem configuration"

  # Time and space discretization
  T: 1.0  # Time horizon
  Nx: 50  # Spatial grid points
  Nt: 30  # Time grid points

  # Spatial domain
  domain:
    x_min: 0.0
    x_max: 1.0
    boundary_buffer: 0.0  # Additional boundary space

  # Default initial condition
  initial_condition:
    type: "gaussian"
    parameters:
      gaussian:
        center: 0.5
        width: 0.1
        amplitude: 1.0
      uniform:
        level: 1.0
      delta:
        position: 0.5
      bimodal:
        centers: [0.3, 0.7]
        widths: [0.1, 0.1]
        weights: [1.0, 1.0]

  # Default boundary conditions
  boundary_conditions:
    m:  # Density boundary conditions
      type: "no_flux"  # no_flux, dirichlet, neumann
      left_value: 0.0
      right_value: 0.0
    u:  # Value function boundary conditions
      type: "neumann"  # dirichlet, neumann
      left_value: 0.0
      right_value: 0.0

  # Physical parameters
  parameters:
    diffusion_coefficient: 0.1
    discount_factor: 0.0

# Cost structure
cost:
  # Running cost L(x, u, m)
  running_cost:
    state_dependent: true
    control_dependent: true
    density_dependent: true

  # Terminal cost g(x)
  terminal_cost:
    enabled: true
    type: "quadratic"  # quadratic, linear, custom

# Numerical parameters
numerics:
  grid:
    uniform_spacing: true
    adaptive_refinement: false

  time_stepping:
    scheme: "implicit_euler"  # explicit_euler, implicit_euler, crank_nicolson
    adaptive_dt: false

  regularization:
    density_floor: 1.0e-8  # Minimum density value
    value_clipping: false
    control_bounds:
      enabled: false
      min_value: -10.0
      max_value: 10.0
