# Towel on Beach Problem Configuration
# Spatial competition with crowd aversion

problem:
  name: "towel_on_beach"
  type: "spatial_competition"
  description: "Spatial competition model with proximity-congestion trade-off"
  
  # Grid configuration
  T: 2.0
  Nx: 80
  Nt: 40
  
  # Spatial domain
  domain:
    x_min: 0.0
    x_max: 1.0
  
  # Problem parameters
  parameters:
    stall_position: 0.6
    crowd_aversion: ${lambda}  # Parameter interpolation
    noise_level: 0.1
    movement_cost_weight: 0.5
  
  # Initial conditions
  initial_condition:
    type: ${init_type:uniform}  # Default to uniform if not specified
    parameters:
      gaussian:
        center: ${init_center:0.2}
        width: 0.05
      gaussian_left:
        center: 0.2
        width: 0.05
      gaussian_right:
        center: 0.8
        width: 0.05
      uniform: {}
      bimodal:
        centers: [0.3, 0.7]
        widths: [0.03, 0.03]
        weights: [1.0, 1.0]
  
  # Boundary conditions
  boundary_conditions:
    m:
      type: "no_flux"
    u:
      type: "neumann"
      left_value: 0.0
      right_value: 0.0

# Running cost specification
cost:
  proximity_weight: 1.0
  congestion_weight: ${problem.parameters.crowd_aversion}
  movement_weight: ${problem.parameters.movement_cost_weight}

# Terminal cost
terminal_cost:
  type: "distance"
  target_position: ${problem.parameters.stall_position}
  weight: 0.5