# Solver Configuration
# MFG solver parameters and methods

solver:
  type: "fixed_point"
  max_iterations: 100
  tolerance: 1.0e-6
  damping: 0.5
  backend: "numpy"  # numpy, jax
  
  # Convergence monitoring
  convergence:
    check_frequency: 10
    patience: 20
    min_improvement: 1.0e-8
    
  # HJB solver configuration
  hjb:
    method: "gfdm"  # gfdm, fdm, semi_lagrangian
    boundary_handling: "penalty"
    penalty_weight: 1000.0
    
    # GFDM-specific parameters
    gfdm:
      stencil_size: 5
      regularization: 1.0e-12
      smart_qp: true
      optimization_tolerance: 1.0e-10
    
    # Newton solver for HJB
    newton:
      max_iterations: 20
      tolerance: 1.0e-8
      line_search: true
      alpha_min: 0.01
      alpha_max: 1.0
      backtrack_factor: 0.5
  
  # Fokker-Planck solver configuration  
  fp:
    method: "fdm"  # fdm, particle
    upwind_scheme: "central"  # upwind, central, eno
    
    # Particle method parameters
    particle:
      n_particles: 1000
      dt_factor: 0.1
      diffusion_scheme: "euler_maruyama"
    
    # FDM parameters
    fdm:
      spatial_scheme: "central"
      time_scheme: "implicit_euler"
      cfl_factor: 0.5

# Performance optimization
optimization:
  use_compiled_functions: true
  cache_matrices: true
  parallel_computation: false
  memory_efficient: true

# Debugging and monitoring
debug:
  save_iterations: false
  plot_convergence: false
  verbose_output: false
  profiling: false