name: Check Ruff Version Updates

# Automated check for ruff updates - runs monthly
# Creates a PR when new stable ruff version is available

on:
  schedule:
    # Run on first day of each month at 9 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  check-ruff-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get current ruff version
        id: current
        run: |
          CURRENT_VERSION=$(grep -A 1 'astral-sh/ruff-pre-commit' .pre-commit-config.yaml | grep 'rev:' | sed 's/.*v//' | tr -d ' ')
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current ruff version: $CURRENT_VERSION"

      - name: Get latest ruff version
        id: latest
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/astral-sh/ruff/releases/latest | jq -r .tag_name | sed 's/v//')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "Latest ruff version: $LATEST_VERSION"

      - name: Compare versions
        id: compare
        run: |
          CURRENT="${{ steps.current.outputs.version }}"
          LATEST="${{ steps.latest.outputs.version }}"

          if [ "$CURRENT" = "$LATEST" ]; then
            echo "needs_update=false" >> $GITHUB_OUTPUT
            echo "✅ Ruff is up to date (v$CURRENT)"
          else
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "🆕 Update available: v$CURRENT → v$LATEST"
          fi

      - name: Install ruff latest version
        if: steps.compare.outputs.needs_update == 'true'
        run: |
          pip install ruff==${{ steps.latest.outputs.version }}

      - name: Update configuration files
        if: steps.compare.outputs.needs_update == 'true'
        run: |
          LATEST="${{ steps.latest.outputs.version }}"

          # Update .pre-commit-config.yaml
          sed -i "s/rev: v[0-9.]\+/rev: v$LATEST/" .pre-commit-config.yaml

          # Update CI workflow
          sed -i "s/ruff==[0-9.]\+/ruff==$LATEST/" .github/workflows/modern_quality.yml

          echo "Updated ruff version to $LATEST"

      - name: Run ruff format
        if: steps.compare.outputs.needs_update == 'true'
        run: |
          ruff format mfg_pde/ || true

      - name: Generate changelog snippet
        if: steps.compare.outputs.needs_update == 'true'
        id: changelog
        run: |
          CURRENT="${{ steps.current.outputs.version }}"
          LATEST="${{ steps.latest.outputs.version }}"

          cat > /tmp/ruff_changes.md << 'EOF'
          ## Ruff Update: v$CURRENT → v$LATEST

          This PR updates ruff to the latest stable version.

          ### Changes
          - Updated `.pre-commit-config.yaml`: `v$CURRENT` → `v$LATEST`
          - Updated `.github/workflows/modern_quality.yml`: `$CURRENT` → `$LATEST`
          - Applied formatting changes (if any)

          ### Review Checklist
          - [ ] Review formatting changes
          - [ ] Run local tests: `pytest tests/`
          - [ ] Check pre-commit hooks: `pre-commit run --all-files`

          ### Ruff Release Notes
          See: https://github.com/astral-sh/ruff/releases/tag/v$LATEST

          ---

          🤖 This PR was automatically generated by the ruff update checker.
          📅 Scheduled check runs monthly on the 1st.
          🔧 To run manually: Actions → Check Ruff Version Updates → Run workflow
          EOF

          sed -i "s/\$CURRENT/$CURRENT/g" /tmp/ruff_changes.md
          sed -i "s/\$LATEST/$LATEST/g" /tmp/ruff_changes.md

      - name: Create Pull Request
        if: steps.compare.outputs.needs_update == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: Update ruff from v${{ steps.current.outputs.version }} to v${{ steps.latest.outputs.version }}

            Automated ruff version update with formatting changes.

            🤖 Generated by ruff update checker
          branch: chore/update-ruff-${{ steps.latest.outputs.version }}
          delete-branch: true
          title: 'chore: Update ruff to v${{ steps.latest.outputs.version }}'
          body-path: /tmp/ruff_changes.md
          labels: |
            dependencies
            tooling
            automated

      - name: Summary
        run: |
          CURRENT="${{ steps.current.outputs.version }}"
          LATEST="${{ steps.latest.outputs.version }}"
          NEEDS_UPDATE="${{ steps.compare.outputs.needs_update }}"

          if [ "$NEEDS_UPDATE" = "true" ]; then
            echo "✅ Created PR to update ruff: v$CURRENT → v$LATEST"
            echo "📋 Review the PR and merge when ready"
          else
            echo "✅ Ruff is up to date at v$CURRENT"
            echo "📅 Next check: 1st of next month"
          fi
